// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util.proto

package com.yourgamecompany;

public final class Util {
  private Util() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yourgamecompany.Time)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 seconds = 1;</code>
     * @return Whether the seconds field is set.
     */
    boolean hasSeconds();
    /**
     * <code>required int32 seconds = 1;</code>
     * @return The seconds.
     */
    int getSeconds();

    /**
     * <code>required int32 minutes = 2;</code>
     * @return Whether the minutes field is set.
     */
    boolean hasMinutes();
    /**
     * <code>required int32 minutes = 2;</code>
     * @return The minutes.
     */
    int getMinutes();
  }
  /**
   * Protobuf type {@code com.yourgamecompany.Time}
   */
  public static final class Time extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yourgamecompany.Time)
      TimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Time.newBuilder() to construct.
    private Time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Time() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Time();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Time(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              seconds_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              minutes_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yourgamecompany.Util.internal_static_com_yourgamecompany_Time_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yourgamecompany.Util.internal_static_com_yourgamecompany_Time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yourgamecompany.Util.Time.class, com.yourgamecompany.Util.Time.Builder.class);
    }

    private int bitField0_;
    public static final int SECONDS_FIELD_NUMBER = 1;
    private int seconds_;
    /**
     * <code>required int32 seconds = 1;</code>
     * @return Whether the seconds field is set.
     */
    @java.lang.Override
    public boolean hasSeconds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 seconds = 1;</code>
     * @return The seconds.
     */
    @java.lang.Override
    public int getSeconds() {
      return seconds_;
    }

    public static final int MINUTES_FIELD_NUMBER = 2;
    private int minutes_;
    /**
     * <code>required int32 minutes = 2;</code>
     * @return Whether the minutes field is set.
     */
    @java.lang.Override
    public boolean hasMinutes() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 minutes = 2;</code>
     * @return The minutes.
     */
    @java.lang.Override
    public int getMinutes() {
      return minutes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSeconds()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinutes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, seconds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, minutes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seconds_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minutes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yourgamecompany.Util.Time)) {
        return super.equals(obj);
      }
      com.yourgamecompany.Util.Time other = (com.yourgamecompany.Util.Time) obj;

      if (hasSeconds() != other.hasSeconds()) return false;
      if (hasSeconds()) {
        if (getSeconds()
            != other.getSeconds()) return false;
      }
      if (hasMinutes() != other.hasMinutes()) return false;
      if (hasMinutes()) {
        if (getMinutes()
            != other.getMinutes()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSeconds()) {
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getSeconds();
      }
      if (hasMinutes()) {
        hash = (37 * hash) + MINUTES_FIELD_NUMBER;
        hash = (53 * hash) + getMinutes();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yourgamecompany.Util.Time parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.Time parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.Time parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yourgamecompany.Util.Time parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.Time parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.Time parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yourgamecompany.Util.Time prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yourgamecompany.Time}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yourgamecompany.Time)
        com.yourgamecompany.Util.TimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_Time_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_Time_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yourgamecompany.Util.Time.class, com.yourgamecompany.Util.Time.Builder.class);
      }

      // Construct using com.yourgamecompany.Util.Time.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seconds_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        minutes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_Time_descriptor;
      }

      @java.lang.Override
      public com.yourgamecompany.Util.Time getDefaultInstanceForType() {
        return com.yourgamecompany.Util.Time.getDefaultInstance();
      }

      @java.lang.Override
      public com.yourgamecompany.Util.Time build() {
        com.yourgamecompany.Util.Time result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yourgamecompany.Util.Time buildPartial() {
        com.yourgamecompany.Util.Time result = new com.yourgamecompany.Util.Time(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.seconds_ = seconds_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minutes_ = minutes_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yourgamecompany.Util.Time) {
          return mergeFrom((com.yourgamecompany.Util.Time)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yourgamecompany.Util.Time other) {
        if (other == com.yourgamecompany.Util.Time.getDefaultInstance()) return this;
        if (other.hasSeconds()) {
          setSeconds(other.getSeconds());
        }
        if (other.hasMinutes()) {
          setMinutes(other.getMinutes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSeconds()) {
          return false;
        }
        if (!hasMinutes()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yourgamecompany.Util.Time parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yourgamecompany.Util.Time) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seconds_ ;
      /**
       * <code>required int32 seconds = 1;</code>
       * @return Whether the seconds field is set.
       */
      @java.lang.Override
      public boolean hasSeconds() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 seconds = 1;</code>
       * @return The seconds.
       */
      @java.lang.Override
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>required int32 seconds = 1;</code>
       * @param value The seconds to set.
       * @return This builder for chaining.
       */
      public Builder setSeconds(int value) {
        bitField0_ |= 0x00000001;
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seconds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeconds() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seconds_ = 0;
        onChanged();
        return this;
      }

      private int minutes_ ;
      /**
       * <code>required int32 minutes = 2;</code>
       * @return Whether the minutes field is set.
       */
      @java.lang.Override
      public boolean hasMinutes() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 minutes = 2;</code>
       * @return The minutes.
       */
      @java.lang.Override
      public int getMinutes() {
        return minutes_;
      }
      /**
       * <code>required int32 minutes = 2;</code>
       * @param value The minutes to set.
       * @return This builder for chaining.
       */
      public Builder setMinutes(int value) {
        bitField0_ |= 0x00000002;
        minutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 minutes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinutes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minutes_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yourgamecompany.Time)
    }

    // @@protoc_insertion_point(class_scope:com.yourgamecompany.Time)
    private static final com.yourgamecompany.Util.Time DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yourgamecompany.Util.Time();
    }

    public static com.yourgamecompany.Util.Time getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Time>
        PARSER = new com.google.protobuf.AbstractParser<Time>() {
      @java.lang.Override
      public Time parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Time(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Time> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Time> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yourgamecompany.Util.Time getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleDateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yourgamecompany.SimpleDate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 year = 1;</code>
     * @return Whether the year field is set.
     */
    boolean hasYear();
    /**
     * <code>required int32 year = 1;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>required int32 month = 2;</code>
     * @return Whether the month field is set.
     */
    boolean hasMonth();
    /**
     * <code>required int32 month = 2;</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <code>required int32 day = 3;</code>
     * @return Whether the day field is set.
     */
    boolean hasDay();
    /**
     * <code>required int32 day = 3;</code>
     * @return The day.
     */
    int getDay();
  }
  /**
   * Protobuf type {@code com.yourgamecompany.SimpleDate}
   */
  public static final class SimpleDate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yourgamecompany.SimpleDate)
      SimpleDateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleDate.newBuilder() to construct.
    private SimpleDate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleDate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleDate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleDate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              year_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              month_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              day_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yourgamecompany.Util.internal_static_com_yourgamecompany_SimpleDate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yourgamecompany.Util.internal_static_com_yourgamecompany_SimpleDate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yourgamecompany.Util.SimpleDate.class, com.yourgamecompany.Util.SimpleDate.Builder.class);
    }

    private int bitField0_;
    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    /**
     * <code>required int32 year = 1;</code>
     * @return Whether the year field is set.
     */
    @java.lang.Override
    public boolean hasYear() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 year = 1;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>required int32 month = 2;</code>
     * @return Whether the month field is set.
     */
    @java.lang.Override
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 month = 2;</code>
     * @return The month.
     */
    @java.lang.Override
    public int getMonth() {
      return month_;
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private int day_;
    /**
     * <code>required int32 day = 3;</code>
     * @return Whether the day field is set.
     */
    @java.lang.Override
    public boolean hasDay() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 day = 3;</code>
     * @return The day.
     */
    @java.lang.Override
    public int getDay() {
      return day_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasYear()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMonth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, year_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, month_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, day_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, year_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, day_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yourgamecompany.Util.SimpleDate)) {
        return super.equals(obj);
      }
      com.yourgamecompany.Util.SimpleDate other = (com.yourgamecompany.Util.SimpleDate) obj;

      if (hasYear() != other.hasYear()) return false;
      if (hasYear()) {
        if (getYear()
            != other.getYear()) return false;
      }
      if (hasMonth() != other.hasMonth()) return false;
      if (hasMonth()) {
        if (getMonth()
            != other.getMonth()) return false;
      }
      if (hasDay() != other.hasDay()) return false;
      if (hasDay()) {
        if (getDay()
            != other.getDay()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasYear()) {
        hash = (37 * hash) + YEAR_FIELD_NUMBER;
        hash = (53 * hash) + getYear();
      }
      if (hasMonth()) {
        hash = (37 * hash) + MONTH_FIELD_NUMBER;
        hash = (53 * hash) + getMonth();
      }
      if (hasDay()) {
        hash = (37 * hash) + DAY_FIELD_NUMBER;
        hash = (53 * hash) + getDay();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yourgamecompany.Util.SimpleDate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.SimpleDate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yourgamecompany.Util.SimpleDate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yourgamecompany.Util.SimpleDate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yourgamecompany.SimpleDate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yourgamecompany.SimpleDate)
        com.yourgamecompany.Util.SimpleDateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_SimpleDate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_SimpleDate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yourgamecompany.Util.SimpleDate.class, com.yourgamecompany.Util.SimpleDate.Builder.class);
      }

      // Construct using com.yourgamecompany.Util.SimpleDate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        month_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yourgamecompany.Util.internal_static_com_yourgamecompany_SimpleDate_descriptor;
      }

      @java.lang.Override
      public com.yourgamecompany.Util.SimpleDate getDefaultInstanceForType() {
        return com.yourgamecompany.Util.SimpleDate.getDefaultInstance();
      }

      @java.lang.Override
      public com.yourgamecompany.Util.SimpleDate build() {
        com.yourgamecompany.Util.SimpleDate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yourgamecompany.Util.SimpleDate buildPartial() {
        com.yourgamecompany.Util.SimpleDate result = new com.yourgamecompany.Util.SimpleDate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.year_ = year_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.month_ = month_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.day_ = day_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yourgamecompany.Util.SimpleDate) {
          return mergeFrom((com.yourgamecompany.Util.SimpleDate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yourgamecompany.Util.SimpleDate other) {
        if (other == com.yourgamecompany.Util.SimpleDate.getDefaultInstance()) return this;
        if (other.hasYear()) {
          setYear(other.getYear());
        }
        if (other.hasMonth()) {
          setMonth(other.getMonth());
        }
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasYear()) {
          return false;
        }
        if (!hasMonth()) {
          return false;
        }
        if (!hasDay()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yourgamecompany.Util.SimpleDate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yourgamecompany.Util.SimpleDate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int year_ ;
      /**
       * <code>required int32 year = 1;</code>
       * @return Whether the year field is set.
       */
      @java.lang.Override
      public boolean hasYear() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 year = 1;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>required int32 year = 1;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        bitField0_ |= 0x00000001;
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 year = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>required int32 month = 2;</code>
       * @return Whether the month field is set.
       */
      @java.lang.Override
      public boolean hasMonth() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 month = 2;</code>
       * @return The month.
       */
      @java.lang.Override
      public int getMonth() {
        return month_;
      }
      /**
       * <code>required int32 month = 2;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {
        bitField0_ |= 0x00000002;
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 month = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        month_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <code>required int32 day = 3;</code>
       * @return Whether the day field is set.
       */
      @java.lang.Override
      public boolean hasDay() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 day = 3;</code>
       * @return The day.
       */
      @java.lang.Override
      public int getDay() {
        return day_;
      }
      /**
       * <code>required int32 day = 3;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        bitField0_ |= 0x00000004;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 day = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        day_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yourgamecompany.SimpleDate)
    }

    // @@protoc_insertion_point(class_scope:com.yourgamecompany.SimpleDate)
    private static final com.yourgamecompany.Util.SimpleDate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yourgamecompany.Util.SimpleDate();
    }

    public static com.yourgamecompany.Util.SimpleDate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleDate>
        PARSER = new com.google.protobuf.AbstractParser<SimpleDate>() {
      @java.lang.Override
      public SimpleDate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleDate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleDate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleDate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yourgamecompany.Util.SimpleDate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yourgamecompany_Time_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yourgamecompany_Time_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yourgamecompany_SimpleDate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yourgamecompany_SimpleDate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nutil.proto\022\023com.yourgamecompany\"(\n\004Tim" +
      "e\022\017\n\007seconds\030\001 \002(\005\022\017\n\007minutes\030\002 \002(\005\"6\n\nS" +
      "impleDate\022\014\n\004year\030\001 \002(\005\022\r\n\005month\030\002 \002(\005\022\013" +
      "\n\003day\030\003 \002(\005B\033\n\023com.yourgamecompanyB\004Util"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_yourgamecompany_Time_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yourgamecompany_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yourgamecompany_Time_descriptor,
        new java.lang.String[] { "Seconds", "Minutes", });
    internal_static_com_yourgamecompany_SimpleDate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yourgamecompany_SimpleDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yourgamecompany_SimpleDate_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
